"use client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/utils/context/auth-provider";
import StyledComponentsRegistry from "../../lib/registery";
import Layout from "@/components/Layout/Layout";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      refetchInterval: false,
    },
  },
});
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryClientProvider client={queryClient}>
      <AuthProvider>
        <StyledComponentsRegistry>
          <html lang="en">
            <body className={inter.className}>
              <Layout>{children}</Layout>
            </body>
          </html>
        </StyledComponentsRegistry>
      </AuthProvider>
    </QueryClientProvider>
  );
}
